open Ppxlib

let process_type_decl_attribute x : string= ""
let process_type_decl_attributes x : string= "attributes"
let process_type_decl_binding_op x = "process_type_decl_binding_op"
let process_type_decl_bool x : string= "bool" 
let process_type_decl_class_expr_desc x = "process_type_decl_class_expr_desc"
let process_type_decl_class_field_desc x = "process_type_decl_class_field_desc"
let process_type_decl_class_type_desc x = "process_type_decl_class_type_desc"
let process_type_decl_class_type_field_desc x = "process_type_decl_class_type_field_desc"
let process_type_decl_constructor_arguments x = "process_type_decl_constructor_arguments"
let process_type_decl_core_type x = "process_type_decl_core_type" 
let process_type_decl_core_type_desc x : string= "core_Type_desc" 
let process_type_decl_directive_argument_desc x = "process_type_decl_directive_argument_desc"
let process_type_decl_expression x : string= "x"
let process_type_decl_expression_desc x = "process_type_decl_expression_desc"
let process_type_decl_extension x : string= "x"
let process_type_decl_extension_constructor x  = "process_type_decl_extension_constructor"
let process_type_decl_extension_constructor_kind x = "process_type_decl_extension_constructor_kind"
let process_type_decl_functor_parameter x : string= "x"
let process_type_decl_include_declaration x : string= "x"
let process_type_decl_int x : string= string_of_int(x) 
let process_type_decl_list x : string = "x"
let process_type_decl_loc x : string= "loc"
let process_type_decl_location x : string= "location"
 let process_type_decl_location_stack x = "process_type_decl_location_stack" 
let process_type_decl_longident x : string= "x"
let process_type_decl_longident_loc x : string = "x"
let process_type_decl_module_binding x : string= "x"
let process_type_decl_module_expr x : string= "x"
let process_type_decl_module_expr_desc x = "process_type_decl_module_expr_desc"
let process_type_decl_module_type x : string= "x"
let process_type_decl_module_type_declaration x : string= "x"
let process_type_decl_module_type_desc x = "process_type_decl_module_type_desc"
let process_type_decl_mutable_flag x = "process_type_decl_mutable_flag"
let process_type_decl_object_field_desc x = "process_type_decl_object_field_desc"
let process_type_decl_open_declaration x : string= "x"
let process_type_decl_option x: string = "x"
let process_type_decl_override_flag x = "process_type_decl_override_flag"
let process_type_decl_pattern  x = "process_type_decl_pattern"
let process_type_decl_pattern_desc x = "process_type_decl_pattern_desc"

(* FIXME this should have been generated *)
let process_type_decl_payload x : string= "process_type_decl_payload"  
let process_type_decl_position x : string= "post"
let process_type_decl_private_flag x = "process_type_decl_private_flag"
let process_type_decl_rec_flag x : string= "x"
let process_type_decl_row_field_desc x : string= "process_type_decl_row_field_desc"
let process_type_decl_signature_item_desc x = "process_type_decl_signature_item_desc"
let process_type_decl_structure x : string= "x"
let process_type_decl_structure_item_desc x = "process_type_decl_structure_item_desc"
let process_type_decl_toplevel_directive x : string= "x"
let process_type_decl_type_declaration x : string= "x"
let process_type_decl_type_exception x : string= "x"
let process_type_decl_type_extension x : string= "x"
let process_type_decl_type_kind x = "process_type_decl_type_kind"
let process_type_decl_value_description x : string= "x"
 let process_type_decl_var_name x : string= "var_name"
let process_type_decl_virtual_flag x = "process_type_decl_virtual_flag"
let process_type_decl_string x : string= "x"


 let process_type_decl_position (x:position):string = match x with {pos_fname(* string*);pos_lnum(* int*);pos_bol(* int*);pos_cnum(* int*)} ->(process_type_decl_string pos_fname)^(process_type_decl_int pos_lnum)^(process_type_decl_int pos_bol)^(process_type_decl_int pos_cnum) 
 let process_type_decl_location (x:location):string = match x with {loc_start(* position*);loc_end(* position*);loc_ghost(* bool*)} ->(process_type_decl_position loc_start)^(process_type_decl_position loc_end)^(process_type_decl_bool loc_ghost) 
 let process_type_decl_loc (x):string = match x with {txt(* var_name*);loc(* location*)} ->(process_type_decl_var_name txt)^(process_type_decl_location loc) 
 let process_type_decl_attribute (x:attribute):string = match x with {attr_name(* loc*);attr_payload(* payload*);attr_loc(* location*)} ->(process_type_decl_loc attr_name)^(process_type_decl_payload attr_payload)^(process_type_decl_location attr_loc) 
 let process_type_decl_core_type (x:core_type):string = match x with {ptyp_desc(* core_type_desc*);ptyp_loc(* location*);ptyp_loc_stack(* location_stack*);ptyp_attributes(* attributes*)} ->(process_type_decl_core_type_desc ptyp_desc)^(process_type_decl_location ptyp_loc)^(process_type_decl_location_stack ptyp_loc_stack)^(process_type_decl_attributes ptyp_attributes) 
 let process_type_decl_row_field (x:row_field):string = match x with {prf_desc(* row_field_desc*);prf_loc(* location*);prf_attributes(* attributes*)} ->(process_type_decl_row_field_desc prf_desc)^(process_type_decl_location prf_loc)^(process_type_decl_attributes prf_attributes) 
 let process_type_decl_object_field (x:object_field):string = match x with {pof_desc(* object_field_desc*);pof_loc(* location*);pof_attributes(* attributes*)} ->(process_type_decl_object_field_desc pof_desc)^(process_type_decl_location pof_loc)^(process_type_decl_attributes pof_attributes) 
 let process_type_decl_pattern (x:pattern):string = match x with {ppat_desc(* pattern_desc*);ppat_loc(* location*);ppat_loc_stack(* location_stack*);ppat_attributes(* attributes*)} ->(process_type_decl_pattern_desc ppat_desc)^(process_type_decl_location ppat_loc)^(process_type_decl_location_stack ppat_loc_stack)^(process_type_decl_attributes ppat_attributes) 
 let process_type_decl_expression (x:expression):string = match x with {pexp_desc(* expression_desc*);pexp_loc(* location*);pexp_loc_stack(* location_stack*);pexp_attributes(* attributes*)} ->(process_type_decl_expression_desc pexp_desc)^(process_type_decl_location pexp_loc)^(process_type_decl_location_stack pexp_loc_stack)^(process_type_decl_attributes pexp_attributes) 
 let process_type_decl_case (x:case):string = match x with {pc_lhs(* pattern*);pc_guard(* option*);pc_rhs(* expression*)} ->(process_type_decl_pattern pc_lhs)^(process_type_decl_option pc_guard)^(process_type_decl_expression pc_rhs) 
 let process_type_decl_letop (x:letop):string = match x with {let_(* binding_op*);ands(* list*);body(* expression*)} ->(process_type_decl_binding_op let_)^(process_type_decl_list ands)^(process_type_decl_expression body) 
 let process_type_decl_binding_op (x:binding_op):string = match x with {pbop_op(* loc*);pbop_pat(* pattern*);pbop_exp(* expression*);pbop_loc(* location*)} ->(process_type_decl_loc pbop_op)^(process_type_decl_pattern pbop_pat)^(process_type_decl_expression pbop_exp)^(process_type_decl_location pbop_loc) 
 let process_type_decl_value_description (x:value_description):string = match x with {pval_name(* loc*);pval_type(* core_type*);pval_prim(* list*);pval_attributes(* attributes*);pval_loc(* location*)} ->(process_type_decl_loc pval_name)^(process_type_decl_core_type pval_type)^(process_type_decl_list pval_prim)^(process_type_decl_attributes pval_attributes)^(process_type_decl_location pval_loc) 
 let process_type_decl_type_declaration (x:type_declaration):string = match x with {ptype_name(* loc*);ptype_params(* list*);ptype_cstrs(* list*);ptype_kind(* type_kind*);ptype_private(* private_flag*);ptype_manifest(* option*);ptype_attributes(* attributes*);ptype_loc(* location*)} ->(process_type_decl_loc ptype_name)^(process_type_decl_list ptype_params)^(process_type_decl_list ptype_cstrs)^(process_type_decl_type_kind ptype_kind)^(process_type_decl_private_flag ptype_private)^(process_type_decl_option ptype_manifest)^(process_type_decl_attributes ptype_attributes)^(process_type_decl_location ptype_loc) 
 let process_type_decl_label_declaration (x:label_declaration):string = match x with {pld_name(* loc*);pld_mutable(* mutable_flag*);pld_type(* core_type*);pld_loc(* location*);pld_attributes(* attributes*)} ->(process_type_decl_loc pld_name)^(process_type_decl_mutable_flag pld_mutable)^(process_type_decl_core_type pld_type)^(process_type_decl_location pld_loc)^(process_type_decl_attributes pld_attributes) 
 let process_type_decl_constructor_declaration (x:constructor_declaration):string = match x with {pcd_name(* loc*);pcd_vars(* list*);pcd_args(* constructor_arguments*);pcd_res(* option*);pcd_loc(* location*);pcd_attributes(* attributes*)} ->(process_type_decl_loc pcd_name)^(process_type_decl_list pcd_vars)^(process_type_decl_constructor_arguments pcd_args)^(process_type_decl_option pcd_res)^(process_type_decl_location pcd_loc)^(process_type_decl_attributes pcd_attributes) 
 let process_type_decl_type_extension (x:type_extension):string = match x with {ptyext_path(* longident_loc*);ptyext_params(* list*);ptyext_constructors(* list*);ptyext_private(* private_flag*);ptyext_loc(* location*);ptyext_attributes(* attributes*)} ->(process_type_decl_longident_loc ptyext_path)^(process_type_decl_list ptyext_params)^(process_type_decl_list ptyext_constructors)^(process_type_decl_private_flag ptyext_private)^(process_type_decl_location ptyext_loc)^(process_type_decl_attributes ptyext_attributes) 
 let process_type_decl_extension_constructor (x:extension_constructor):string = match x with {pext_name(* loc*);pext_kind(* extension_constructor_kind*);pext_loc(* location*);pext_attributes(* attributes*)} ->(process_type_decl_loc pext_name)^(process_type_decl_extension_constructor_kind pext_kind)^(process_type_decl_location pext_loc)^(process_type_decl_attributes pext_attributes) 
 let process_type_decl_type_exception (x:type_exception):string = match x with {ptyexn_constructor(* extension_constructor*);ptyexn_loc(* location*);ptyexn_attributes(* attributes*)} ->(process_type_decl_extension_constructor ptyexn_constructor)^(process_type_decl_location ptyexn_loc)^(process_type_decl_attributes ptyexn_attributes) 
 let process_type_decl_class_type (x:class_type):string = match x with {pcty_desc(* class_type_desc*);pcty_loc(* location*);pcty_attributes(* attributes*)} ->(process_type_decl_class_type_desc pcty_desc)^(process_type_decl_location pcty_loc)^(process_type_decl_attributes pcty_attributes) 
 let process_type_decl_class_signature (x:class_signature):string = match x with {pcsig_self(* core_type*);pcsig_fields(* list*)} ->(process_type_decl_core_type pcsig_self)^(process_type_decl_list pcsig_fields) 
 let process_type_decl_class_type_field (x:class_type_field):string = match x with {pctf_desc(* class_type_field_desc*);pctf_loc(* location*);pctf_attributes(* attributes*)} ->(process_type_decl_class_type_field_desc pctf_desc)^(process_type_decl_location pctf_loc)^(process_type_decl_attributes pctf_attributes) 
 let process_type_decl_class_infos (x):string = match x with {pci_virt(* virtual_flag*);pci_params(* list*);pci_name(* loc*);pci_expr(* var_name*);pci_loc(* location*);pci_attributes(* attributes*)} ->(process_type_decl_virtual_flag pci_virt)^(process_type_decl_list pci_params)^(process_type_decl_loc pci_name)^(process_type_decl_var_name pci_expr)^(process_type_decl_location pci_loc)^(process_type_decl_attributes pci_attributes) 
 let process_type_decl_class_expr (x:class_expr):string = match x with {pcl_desc(* class_expr_desc*);pcl_loc(* location*);pcl_attributes(* attributes*)} ->(process_type_decl_class_expr_desc pcl_desc)^(process_type_decl_location pcl_loc)^(process_type_decl_attributes pcl_attributes) 
 let process_type_decl_class_structure (x:class_structure):string = match x with {pcstr_self(* pattern*);pcstr_fields(* list*)} ->(process_type_decl_pattern pcstr_self)^(process_type_decl_list pcstr_fields) 
 let process_type_decl_class_field (x:class_field):string = match x with {pcf_desc(* class_field_desc*);pcf_loc(* location*);pcf_attributes(* attributes*)} ->(process_type_decl_class_field_desc pcf_desc)^(process_type_decl_location pcf_loc)^(process_type_decl_attributes pcf_attributes) 
 let process_type_decl_module_type (x:module_type):string = match x with {pmty_desc(* module_type_desc*);pmty_loc(* location*);pmty_attributes(* attributes*)} ->(process_type_decl_module_type_desc pmty_desc)^(process_type_decl_location pmty_loc)^(process_type_decl_attributes pmty_attributes) 
 let process_type_decl_signature_item (x:signature_item):string = match x with {psig_desc(* signature_item_desc*);psig_loc(* location*)} ->(process_type_decl_signature_item_desc psig_desc)^(process_type_decl_location psig_loc) 
 let process_type_decl_module_declaration (x:module_declaration):string = match x with {pmd_name(* loc*);pmd_type(* module_type*);pmd_attributes(* attributes*);pmd_loc(* location*)} ->(process_type_decl_loc pmd_name)^(process_type_decl_module_type pmd_type)^(process_type_decl_attributes pmd_attributes)^(process_type_decl_location pmd_loc) 
 let process_type_decl_module_substitution (x:module_substitution):string = match x with {pms_name(* loc*);pms_manifest(* longident_loc*);pms_attributes(* attributes*);pms_loc(* location*)} ->(process_type_decl_loc pms_name)^(process_type_decl_longident_loc pms_manifest)^(process_type_decl_attributes pms_attributes)^(process_type_decl_location pms_loc) 
 let process_type_decl_module_type_declaration (x:module_type_declaration):string = match x with {pmtd_name(* loc*);pmtd_type(* option*);pmtd_attributes(* attributes*);pmtd_loc(* location*)} ->(process_type_decl_loc pmtd_name)^(process_type_decl_option pmtd_type)^(process_type_decl_attributes pmtd_attributes)^(process_type_decl_location pmtd_loc) 
 let process_type_decl_open_infos (x):string = match x with {popen_expr(* var_name*);popen_override(* override_flag*);popen_loc(* location*);popen_attributes(* attributes*)} ->(process_type_decl_var_name popen_expr)^(process_type_decl_override_flag popen_override)^(process_type_decl_location popen_loc)^(process_type_decl_attributes popen_attributes) 
 let process_type_decl_include_infos (x):string = match x with {pincl_mod(* var_name*);pincl_loc(* location*);pincl_attributes(* attributes*)} ->(process_type_decl_var_name pincl_mod)^(process_type_decl_location pincl_loc)^(process_type_decl_attributes pincl_attributes) 
 let process_type_decl_module_expr (x:module_expr):string = match x with {pmod_desc(* module_expr_desc*);pmod_loc(* location*);pmod_attributes(* attributes*)} ->(process_type_decl_module_expr_desc pmod_desc)^(process_type_decl_location pmod_loc)^(process_type_decl_attributes pmod_attributes) 
 let process_type_decl_structure_item (x:structure_item):string = match x with {pstr_desc(* structure_item_desc*);pstr_loc(* location*)} ->(process_type_decl_structure_item_desc pstr_desc)^(process_type_decl_location pstr_loc) 
 let process_type_decl_value_binding (x:value_binding):string = match x with {pvb_pat(* pattern*);pvb_expr(* expression*);pvb_attributes(* attributes*);pvb_loc(* location*)} ->(process_type_decl_pattern pvb_pat)^(process_type_decl_expression pvb_expr)^(process_type_decl_attributes pvb_attributes)^(process_type_decl_location pvb_loc) 
 let process_type_decl_module_binding (x:module_binding):string = match x with {pmb_name(* loc*);pmb_expr(* module_expr*);pmb_attributes(* attributes*);pmb_loc(* location*)} ->(process_type_decl_loc pmb_name)^(process_type_decl_module_expr pmb_expr)^(process_type_decl_attributes pmb_attributes)^(process_type_decl_location pmb_loc) 
 let process_type_decl_toplevel_directive (x:toplevel_directive):string = match x with {pdir_name(* loc*);pdir_arg(* option*);pdir_loc(* location*)} ->(process_type_decl_loc pdir_name)^(process_type_decl_option pdir_arg)^(process_type_decl_location pdir_loc) 
 let process_type_decl_directive_argument (x:directive_argument):string = match x with {pdira_desc(* directive_argument_desc*);pdira_loc(* location*)} ->(process_type_decl_directive_argument_desc pdira_desc)^(process_type_decl_location pdira_loc) 
